# Generated by Django 4.0.6 on 2022-07-19 08:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_of_collage', models.IntegerField()),
                ('date_of_created', models.DateField(auto_now_add=True)),
                ('manger_of_collage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester')], max_length=100)),
                ('date_of_start', models.DateField()),
                ('date_of_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_hour', models.IntegerField()),
                ('date_of_created', models.DateField(auto_now_add=True)),
                ('collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.collage')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10)),
                ('slug', models.SlugField(unique=True)),
                ('id_course', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.collage')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.major')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
            ],
        ),
    ]
