# Generated by Django 4.0.6 on 2022-07-21 12:00

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_student_gender_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoSemster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='year')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, populate_from=['semster', 'year'], unique=True)),
                ('semster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
            ],
        ),
        migrations.CreateModel(
            name='SemsterCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, populate_from=['no_semster', 'coures'], unique=True)),
                ('coures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courses')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff')),
                ('no_semster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nosemster')),
                ('semster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
            ],
        ),
    ]
